// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfprcXcZ5eOUt-NvSBny7zIPXtYVWZUaY',
    appId: '1:413037787274:web:f7d85d3118f5ccb6921573',
    messagingSenderId: '413037787274',
    projectId: 'task-manager-application-e4ffe',
    authDomain: 'task-manager-application-e4ffe.firebaseapp.com',
    storageBucket: 'task-manager-application-e4ffe.appspot.com',
    measurementId: 'G-EJ08M5BY6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD34TH4THvkp2QJy7OXaJZ59fXXYC9LIJU',
    appId: '1:413037787274:android:eebac13a9d5c1d5d921573',
    messagingSenderId: '413037787274',
    projectId: 'task-manager-application-e4ffe',
    storageBucket: 'task-manager-application-e4ffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe59rAFdRq6AfbTi8nADl3yFaGqZfma-M',
    appId: '1:413037787274:ios:ef81435e3e4f8b85921573',
    messagingSenderId: '413037787274',
    projectId: 'task-manager-application-e4ffe',
    storageBucket: 'task-manager-application-e4ffe.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe59rAFdRq6AfbTi8nADl3yFaGqZfma-M',
    appId: '1:413037787274:ios:ef81435e3e4f8b85921573',
    messagingSenderId: '413037787274',
    projectId: 'task-manager-application-e4ffe',
    storageBucket: 'task-manager-application-e4ffe.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
